#!/usr/bin/python3
import sys
from src.error_handling import error_handling


def main(argv: list[str]) -> int:
    return error_handling(argv)


if __name__ == '__main__':
    sys.exit(main(sys.argv))
    