#!/usr/bin/python3
import sys
from src.help.display_help import display_help


def main(argv: list[str]) -> int:
    if argv[1] == "-h":
        return display_help()
    return 84


if __name__ == '__main__':
    sys.exit(main(sys.argv))
    