#!/usr/bin/python3
import sys
from src.error_handling import error_handling
from src.help.display_help import display_help


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        return 84
    if argv[1] == "-h":
        return display_help()
    return error_handling(argv)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
